### ISSUE TITLE
Could not resolve ref for gh:data-8/data8assets/master

### ISSUE THREAD

**Issue by liffiton** [jupyterhub/binder#102]
I'm getting the error ``Could not resolve ref for gh:data-8/data8assets/master`` both when using either the "launch binder" badge from the [data8assets](https://github.com/data-8/data8assets) README and when entering the URL for the repository directly into mybinder.org's front page.  I expect it worked at some point or they wouldn't have added the badge to their README.

**Comment by choldgraf** [comment]
hey @liffiton - the binder link that repo is using isn't correct. It's this:

http://mybinder.org/repo/data-8/data8assets

while it should be this:

https://mybinder.org/v2/gh/data-8/data8assets/gh-pages

I'm closing this issue, since this isn't a problem with Binder but with that repository. See https://github.com/data-8/data8assets/issues/6 for follow up
