### ISSUE TITLE
setup.py example repo and documentation

### ISSUE THREAD

**Issue by cranmer** [jupyterhub/binder#114]
@choldgraf suggested I make an issue so we don't forget.

I created an example repo with setup.py here:
https://github.com/cranmer/setup.py
with the expectation that would be added to the binder_examples organization. I'm not sure if it's a problem that the repo is seen as a fork of the original kennethreitz/setup.py repo.

I tried to make the README look like the other examples. I'm also not sure about the name of the repo with the `.` in it. I could also remove the Manifest.in, license files and make setup.py more minimal, but it's kind of a nice example for setup.py as well.

I created PR #113 for the binder docs, the Readme has link pointing to the future home location
https://github.com/binder_examples/setup.py

**Comment by choldgraf** [comment]
Hey! Sorry for the slow uptake - everybody in Jupyterland is in JupyterCon (and I'm actually in Europe for my honeymoon!)

A couple quick points:

1. I imported your repository to `binder-examples`: https://github.com/binder-examples/setup.py
2. I do actually think it'd be useful if we had a super bare-bones `setup.py` + repo instead of one with the complications in this repo. The idea of `binder-examples` is to show the "building blocks" that people can use to accomplish different goals, so each repo should be all about illustrating a single configuration. To that extent I feel like the extra stuff inside `setup.py` that doesn't have to do with specifying requirements does distract a bit. Why not simplify this repo, and add a link that says "for a more complex version of this repository with XXX extra features, see <link to your repo>"?

Let me know what you think! And thanks again for offering this example, I think it'll be helpful for the developer community!

**Comment by betatim** [comment]
I'd :+1: to making the `setup.py` simpler.
