### ISSUE TITLE
ModuleNotFoundError: bs4

### ISSUE THREAD

**Issue by michaelprem** [jupyterhub/binder#121]
Hello!
I am testing mybinder with a little (unfinished) script here:
https://github.com/michaelprem/testInteractive

When trying to open it in mybinder, I get the error message: ModuleNotFoundError: bs4
The package bs4 is in the requirements.txt file, and it is the newest version available. What may the problem be?
Thanks

Michael

**Comment by betatim** [comment]
Currently you repository does not build on mybinder.org due to a dependency's version you specified that doesn't exist for linux.

Your `requirements.txt` looks like you generated it with `pip freeze`. This can generate a set of dependencies that is too specific, especially if you aren't using linux (this is what mybinder.org uses) to generate it.

To get started I would only specify the libraries you explicitly depend on with loose or no version specified. Once you have that working I'd then tighten up the specification by adding version specifications to your dependencies.

**Comment by michaelprem** [comment]
Thanks a lot!
It is still missing the bs4 package, which on my linux installs fine with pip.
 > pip3 install bs4
Requirement already satisfied: bs4 in /home/michaelp/anaconda3/lib/python3.6/site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /home/michaelp/anaconda3/lib/python3.6/site-packages (from bs4) (4.6.0)

There might be some aliasing issue here. Would you know anything about it?
Thanks!!!

**Comment by betatim** [comment]
Your repository https://github.com/michaelprem/testInteractive/tree/97acd29410f5320432f984ba479aa74f35f73a2a builds and I can run ` from bs4 import BeautifulSoup` in it on mybinder.org.

Should we close this issue?

**Comment by michaelprem** [comment]
Strange, here I still get the ModuleNotFoundError: No module named 'bs4'
Also when I run the import line on its own cell.
Also on a different browser.

**Comment by michaelprem** [comment]
Or do you mean this one?
https://hub.mybinder.org/user/michaelprem-testinteractive-f9nboavo/notebooks/TreatBook-interactive1.ipynb

**Comment by choldgraf** [comment]
hmm - importing bs4 seems to run fine for me:

https://mybinder.org/v2/gh/michaelprem/testInteractive/master

**Comment by michaelprem** [comment]
Thanks, Chris! Its working now.
The remaining problem was that I had to ref  lxml explicitly in the requirements.txt file
(had the wrong idea that this was done behind the scenes by bs4.)

Michael

**Comment by choldgraf** [comment]
Great! I'm gonna close this issue as I *think* it's resolved, but if I am wrong then please do feel free to re-open!
