### ISSUE TITLE
Repo with (irrelevant) submodule fails to build

### ISSUE THREAD

**Issue by Atcold** [jupyterhub/binder#187]
Trying to build https://github.com/Atcold/pytorch-Deep-Learning I get the following. The stuff in the `/docs` is for generating the website and does not affect or interact with the rest of the code.
```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerq6f59ba9'...
HEAD is now at 365427a Fix week 1 summaries
Submodule 'jekyllbook' (https://github.com/ebetica/jekyllbook) registered for path 'docs/jekyllbook'
Cloning into '/tmp/repo2dockerq6f59ba9/docs/jekyllbook'...
Submodule path 'docs/jekyllbook': checked out '0b91f97224c2d2fd65b903f29bcf1a3d6e8e3a89'
Error during build: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

**Comment by betatim** [comment]
I just tried it with https://mybinder.org/v2/gh/Atcold/pytorch-Deep-Learning/master (ref: 5a1a8d7c3db4658bc2343a34ba9ad0e2915c7c73) and it starts building after a moment of "cloning".

I don't really recognise the error you got. Is the website repo really big or some such?

We check out all submodules of a repository because some people use them to pull in content and stuff.

**Comment by Atcold** [comment]
Closing due to faulty server issue.
