### ISSUE TITLE
Cannot uninstall terminado, build fails

### ISSUE THREAD

**Issue by astrojuanlu** [jupyterhub/binder#221]
### Bug description

When building https://github.com/astrojuanlu/ie-mbd-advanced-python/, build fails at this step:

```
Attempting uninstall terminado
Found existing installation: terminado 0.8.3
ERROR: Cannot unintstall 'terminado'. It is a distutils installed project and thus...
```

(by the way, I can't seem to be able to copy the text from the build logs...)

The `requirements.txt` contains these lines:

```
$ grep terminado requirements.txt 
ptyprocess==0.6.0         # via pexpect, terminado
terminado==0.9.1          # via notebook
tornado==6.1              # via ipykernel, jupyter-client, notebook, terminado
```

Because they come from pip-compile:

```
$ cat requirements.in 
black==20.8b1
notebook
rise
```

I guess that pinning `terminado` to the version that Binder uses would fix the problem, but I don't think this was needed in the past.

**Comment by betatim** [comment]
Hi there, we try to collect support requests in the forum because it makes them easier to discover and more people see them. It would be good to post this question there instead. It has come up before and got answered but it was in a place that is hard to search (which is why you had little chance of finding it :-/) https://gitter.im/jupyterhub/binder?at=5faba8f0bf955735eb71a11b is probably the answer which would be could to copy into the forum thread about this.

**Comment by astrojuanlu** [comment]
Hi @betatim ! Sure, I had just registered - thanks for the pointer to the chat!

**Comment by astrojuanlu** [comment]
https://discourse.jupyter.org/t/build-errors-when-using-fully-pinned-requirements-txt-coming-from-pip-tools/6821?u=astrojuanlu
