### ISSUE TITLE
doc: mention apt.txt in preparing.rst

### ISSUE THREAD

**Issue by mdeff** [jupyterhub/binder#41]
You should mention the use of an `apt.txt` file in the documentation! It came handy for me to install `gfortran` alongside a standard Python environment defined with a `requirements.txt` file.

I would also add a note or mention the (advanced) possibility of using a `Dockerfile` in `preparing.rst`.

**Comment by mdeff** [comment]
For reference, I used it to enable binder for <https://github.com/mdeff/python_tour_of_data_science>.

**Comment by betatim** [comment]
You know what I am going to say: could you make a PR to add a section about `apt.txt`? The only reason it is missing is that no one has gotten around to writing it down yet.

Dockerfiles are covered in the next section of the docs. Maybe we need to rename the section titles a bit to make it more obvious that one follows after the other. Personally I am Ok with it being a bit difficult to discover that you can use a Dockerfile because it feels like in the past everyone was rushing to making their own, even when they didn't have to. Debugging them is much harder and it is more complex to get right. So from that point of view persuading as many people as possible to not do it is a win for me. At the same time we want to know about people using Dockerfiles to see why it is they are using them so you can move things that are done across many Dockerfiles into a "supported mechanism" (like e.g. apt.txt)

**Comment by choldgraf** [comment]
thanks for pointing that out @mdeff ! It'll be fixed in https://github.com/jupyterhub/binder/pull/47!

**Comment by mdeff** [comment]
Thanks @choldgraf! Making the link with `repo2docker` is indeed the right thing to do. :) Sorry @betatim I could not prepare a PR for this, but I would have missed the big picture anyway...

I totally agree a Dockerfile should be the last resort. I made it once for a Jupyter lab installation, it's indeed very error prone...

Thanks again to you guys for your good work. I'm closing this now.

**Comment by choldgraf** [comment]
thanks for bringing these kinds of issues! Not everybody opens documentation-related issues, but they are *very* helpful!
