### ISSUE TITLE
Documentation 1.0

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binder#5]
We should put together documentation to help users figure out the service, and to point people to other tools in the ecosystem if they're relevant.

I took a first stab at this and it's already merged. See

http://mybinder.readthedocs.io/en/latest

or

docs.mybinder.org  (currently points to the binderhub documentation but this should change soon)

what else should we add? I want this page to be more user-facing (e.g. for people who want to create Binder repos, or who want to use other people's Binder repos, not for people who want to create their own Binder deployments).

**Comment by choldgraf** [comment]
cc' @yuvipanda @willingc @minrk @fperez @freeman-lab

**Comment by willingc** [comment]
It's a bit unfortunate that https://binder.readthedocs.io is taken by another project.

#3 on nomenclature discussion is important to have sooner vs. later to minimize confusion for all.

Since Chris has named the user facing documentation `mybinder`, `mybinder` seems a reasonable  for name for:
- a person (perhaps `content producer`) posting content to be served by a Binder deployment
- a person (perhaps `content consumer`)pressing a button to launch an interactive UI (notebook, jupyterlab, etc) to explore content
- anyone who is considering being either a `content producer or consumer`.

Note: I'm not sure that I like `producer` and `consumer` but they are more specific than `user` which includes those wanting to deploy a BinderHub to serve as well.

**Comment by choldgraf** [comment]
I'm gonna close this one, as the docs are now in place and we're iterating on them currently. We should definitely continue the nomenclature discussion in #3
