### ISSUE TITLE
Build failing on repo with Julia 0.6, NoneType object has no attribute get

### ISSUE THREAD

**Issue by tpoisot** [jupyterhub/binder#73]
I am trying to build the following repo:

https://mybinder.org/v2/gh/tpoisot/ScientificComputingForTheRestOfUs/master

It was working up until last week-ish.

When I try now, the build fails, and the only message I get is:

~~~
Error during build: Build failing on repo with Julia 0.6, NoneType object has no attribute get
~~~

The notebooks run on multiple machines locally.

**Comment by betatim** [comment]
This is probably a problem in `repo2docker` (https://github.com/jupyter/repo2docker). If you want to debug a bit more yourself you can install repo2docker locally and see the `Dockerfile` it generates and watch the build process. `repo2docker` is the tool mybinder.org uses to build.

I'd suggest we move the issue to the repo2docker repository for longer term tracking, Is that Ok with you?

(While this doesn't look like an error related to load, mybinder.org is experience a lot of load from the jupyterlab announcement, so trying to build locally would be a good way to exclude "weird failure due to load".)

**Comment by choldgraf** [comment]
hey all - any movement on this? Looks like it was a `repo2docker` bug but I don't see an issue in that repository of the same nature...

**Comment by minrk** [comment]
Looks like the issue is the fact that there is an empty environment.yml. Is there a reason there's an empty file instead of no environment.yml at all?
