### ISSUE TITLE
Add an example repository to show both Python and R at the same time

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binder#88]
We've had a few people try and install both Python and R at the same time (I think this is relatively common), and they've almost all run into problems. I think we should create an example repository for how to do this with a postBuild file. This would be a stop-gap until a proper "Python+R" buildpack is created.

@betatim have you gotten both of these things installed in the same repo2docker build before?

**Comment by betatim** [comment]
No unfortunately not. Also don't know of a repo that has this. From my experience installing R via conda works but R users don't seem to use conda and so all the R packages you find in conda are outdated :-/

**Comment by choldgraf** [comment]
@betatim so, on this topic do you think the best path forward for people that want *both* R and Python is to either:

1. Install R the "normal" way with `install.R` and `runtime.txt`
2. Install Python manually with `postBuild` commands (e.g. `pip3 install blah blah`)

OR

1. Install R and Python with `conda` and ask people to use the jupyter notebook/lab interface for each?

I can try writing a repo that does this, whichever is better

**Comment by jzf2101** [comment]
What about https://medium.com/@mbussonn/baf064ca1fb6 ?

**Comment by betatim** [comment]
> What about https://medium.com/@mbussonn/baf064ca1fb6 ?

That looks like exactly what we need!

**Comment by jzf2101** [comment]
https://github.com/binder-examples/multi-language-demo is already in binder examples. I'm going to assume we can close @betatim.

**Comment by betatim** [comment]
I'd close this issue.

**Comment by sebkopf** [comment]
@betatim @choldgraf I know this issue is closed but the problem is that this solution only uses R via cell magic rather than allowing separate R and python kernels. [Here is a binder repo example](https://github.com/2018-Computational-Tools/assignment_problem_set) that includes both kernels using the suggested `postBuild` solution (with `template_R.ipynb` and `template_python.ipynb` as example files). If there is a better recommended way for installing both R and python dependencies for use as jupyter kernels, a link to the repo would be much appreciated.

**Comment by choldgraf** [comment]
Thanks for the note @sebkopf - if you've got a better way of installing these it'd be great to see a better example repository for python + R!
